version: "3"
services:
    web:
        container_name: deploy_heroku_with_docker
        build: ./golang
        ports:
            - 8080:8080
        volumes:
            - ./golang:/go/src/app
        tty: true