version: "3"
services:
    web:
        container_name: deploy_heroku_with_docker
        build:
            context: ./golang
            target: DEV
        image: dev
        ports:
            - 8080:8080
        volumes:
            - ./golang:/go/src/app
        tty: true